package src.semantics;

import src.ast.Type;
import src.symbol.Counter;

/**
 * An abstract class representing a binding in the semantic analysis phase.
 * Bindings are used to associate identifiers with their corresponding types in a symbol table.
 */
public abstract class Binding
{
	private Counter counter = Counter.getInstance(); // Counter instance to generate unique counts for each binding
	protected Type type; // The type associated with the binding
	private int count; // A unique count assigned to each binding

	/**
     * Constructor to create a new Binding with a given type.
     * It assigns a unique count to the binding using the Counter instance.
     *
     * @param t The Type associated with the binding.
     */
	public Binding(Type t)
	{
		count = counter.getCount();
		type = t;
	}

	/**
     * Get the Type associated with this binding.
     *
     * @return The Type associated with the binding.
     */
	public Type getType()
	{
		return type;
	}

	/**
     * Get the unique count assigned to this binding.
     * This count is generated by the Counter instance during the binding's creation.
     *
     * @return The unique count associated with the binding.
     */
	@Override
	public String toString()
	{
		return Integer.toString(count);
	}
}