name: Github CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and run tests
        run: mvn clean test